# Generated by Django 5.2.8 on 2026-09-16 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_sala', models.CharField(max_length=20, unique=True, verbose_name='Número da Sala')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('capacidade', models.IntegerField(default=1, verbose_name='Capacidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero_sala'],
            },
        ),
        migrations.CreateModel(
            name='AgendaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_agendada', to='consultas.consulta', verbose_name='Consulta')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Agenda de Sala',
                'verbose_name_plural': 'Agendas de Salas',
                'ordering': ['data', 'hora_inicio'],
                'indexes': [models.Index(fields=['sala', 'data'], name='salas_agend_sala_id_53e516_idx')],
            },
        ),
    ]
