# Generated by Django 5.2.8 on 2026-09-16 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_consulta', models.DateField(verbose_name='Data da Consulta')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('tipo_consulta', models.CharField(choices=[('avaliacao_inicial', 'Avaliação Inicial'), ('retorno', 'Retorno'), ('sessao_grupo', 'Sessão em Grupo'), ('emergencia', 'Emergência')], max_length=30, verbose_name='Tipo de Consulta')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('falta', 'Falta')], default='agendada', max_length=20, verbose_name='Status')),
                ('notas_sessao', models.TextField(blank=True, verbose_name='Notas da Sessão')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_consulta', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_lembrete', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone')], max_length=20, verbose_name='Tipo de Lembrete')),
                ('data_hora_envio', models.DateTimeField(verbose_name='Data/Hora de Envio')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['data_hora_envio'],
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dias_preferidos', models.CharField(blank=True, max_length=100, verbose_name='Dias Preferidos')),
                ('horario_preferido', models.CharField(blank=True, max_length=50, verbose_name='Horário Preferido')),
                ('prioridade', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('normal', 'Normal'), ('baixa', 'Baixa')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('agendada', 'Agendada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_sala', models.CharField(max_length=20, unique=True, verbose_name='Número da Sala')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('capacidade', models.IntegerField(default=1, verbose_name='Capacidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero_sala'],
            },
        ),
    ]
