# Generated by Django 5.2.8 on 2026-09-16 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='profissionais.profissional', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='consultas.consulta', verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='profissional_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_espera', to='profissionais.profissional', verbose_name='Profissional Preferido'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['data_consulta'], name='consultas_c_data_co_eb05c0_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['paciente', 'profissional'], name='consultas_c_pacient_220519_idx'),
        ),
    ]
