# Generated by Django 5.2.8 on 2026-09-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
