# Generated by Django 5.2.8 on 2026-09-16 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('valor_convenio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Convênio')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('convenio', 'Convênio'), ('cheque', 'Cheque')], max_length=30, verbose_name='Método de Pagamento')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('parcialmente_pago', 'Parcialmente Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=30, verbose_name='Status do Pagamento')),
                ('numero_nota', models.CharField(blank=True, max_length=100, verbose_name='Número da Nota')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamentos', to='consultas.consulta', verbose_name='Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamentos',
                'ordering': ['-data_servico'],
            },
        ),
    ]
