# Generated by Django 5.2.8 on 2026-09-16 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('telefones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primeiro_nome', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não-binário'), ('outro', 'Outro'), ('prefiro_nao_informar', 'Prefiro não informar')], max_length=30, verbose_name='Gênero')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-mail')),
                ('contato_emergencia_nome', models.CharField(max_length=150, verbose_name='Nome do Contato de Emergência')),
                ('contato_emergencia_telefone', models.CharField(max_length=20, verbose_name='Telefone do Contato de Emergência')),
                ('convenio', models.CharField(blank=True, max_length=150, verbose_name='Convênio')),
                ('numero_carteirinha', models.CharField(blank=True, max_length=100, verbose_name='Número da Carteirinha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('enderecos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='enderecos.endereco', verbose_name='Endereços')),
                ('telefones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='telefones.telefone', verbose_name='Telefones')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['sobrenome', 'primeiro_nome'],
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_registro', models.DateField(verbose_name='Data do Registro')),
                ('codigo_cid', models.CharField(blank=True, max_length=20, verbose_name='Código CID-10')),
                ('queixa_principal', models.TextField(blank=True, verbose_name='Queixa Principal')),
                ('plano_tratamento', models.TextField(blank=True, verbose_name='Plano de Tratamento')),
                ('evolucao', models.TextField(blank=True, verbose_name='Evolução')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('avaliacao_risco', models.TextField(blank=True, verbose_name='Avaliação de Risco')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios', to='consultas.consulta', verbose_name='Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='pacientes.paciente', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='profissionais.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-data_registro'],
            },
        ),
    ]
