# Generated by Django 5.2.8 on 2026-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_add_tipo_profissional_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['ativo', 'sobrenome', 'primeiro_nome'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissionais',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='profissionais.profissional'),
        ),
    ]
