# Generated by Django 5.2.8 on 2026-09-16 22:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número')),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('celular', 'Celular'), ('comercial', 'Comercial'), ('recado', 'Recado')], max_length=20, verbose_name='Tipo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
