# Generated by Django 5.2.8 on 2026-10-09 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_add_tipo_profissional_data'),
        ('telefones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='pacientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='pacientes.paciente', verbose_name='pacientes'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='profissionais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='profissionais.profissional', verbose_name='profissionais'),
        ),
        migrations.AddConstraint(
            model_name='telefone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pacientes__isnull', False), ('profissionais__isnull', True)), models.Q(('pacientes__isnull', True), ('profissionais__isnull', False)), _connector='OR'), name='telefone_com_um_unico_dono'),
        ),
    ]
